Repository Emplea-do/MobileApp-Xamarin, pull requests merged in 2019-11, with the labels that each got.

#14 Introduced Splash Screen and App Icon
  src/App.iOS/Assets.xcassets/Icon.imageset/Contents.json
  src/App.iOS/Assets.xcassets/Icon.imageset/Icon120-1.png
  src/App.iOS/Assets.xcassets/Icon.imageset/Icon180.png
  src/App.iOS/Assets.xcassets/Icon.imageset/Icon60-1.png
  src/App.iOS/Info.plist
  src/App.iOS/iTunesArtwork
  src/App.iOS/iTunesArtwork@2x
Labels: UI

#17 Crear lista trabajos
  src/App.Android/MainActivity.cs
  src/App.Android/Resources/values/styles.xml
  src/App/App.csproj
  src/App/App.xaml
  src/App/MainShell.xaml
  src/App/Models/JobListModel.cs
  src/App/Services/AppConstant.cs
  src/App/ViewModels/JobsListViewModel.cs
  src/App/ViewModels/SearchViewModel.cs
  src/App/Views/JosbListView.xaml
  src/App/Views/JosbListView.xaml.cs
  src/App/Views/Profile.xaml
  src/App/Views/ProfileView.xaml
  src/App/Views/ProfileView.xaml.cs
  src/App/Views/SearchView.xaml
  src/App/Views/SearchView.xaml.cs
  src/App/Views/SettingsView.xaml
  src/App/Views/SettingsView.xaml.cs
  src/appcenter-pre-build.sh
Labels: UI, enhancement

#21 adding pull request template
  .github/pull_request_template.md
Labels: documentation, enhancement

#16 Adding App icon to Android App
  build/android/emplea-do.keystore
  build/android/emplea-do.txt
  build/ios/Empleado_Xamarin_adhoc.mobileprovision
  build/ios/ios Distribution - Megsoft Consulting- 2020-08-22.p12
  src/App.Android/App.Android.csproj
  src/App.Android/MainActivity.cs
  src/App.Android/Properties/AndroidManifest.xml
  src/App.Android/Resources/Resource.designer.cs
  src/App.Android/Resources/drawable/splash_screen.xml
  src/App.Android/Resources/mipmap-anydpi-v26/icon.xml
  src/App.Android/Resources/mipmap-hdpi/ic_background.png
  src/App.Android/Resources/mipmap-hdpi/ic_foreground.png
  src/App.Android/Resources/mipmap-mdpi/ic_background.png
  src/App.Android/Resources/mipmap-mdpi/ic_foreground.png
  src/App.Android/Resources/mipmap-xhdpi/ic_background.png
  src/App.Android/Resources/mipmap-xhdpi/ic_foreground.png
  src/App.Android/Resources/mipmap-xxhdpi/ic_background.png
  src/App.Android/Resources/mipmap-xxhdpi/ic_foreground.png
  src/App.Android/Resources/mipmap-xxxhdpi/ic_background.png
  src/App.Android/Resources/mipmap-xxxhdpi/ic_foreground.png
  src/App.Android/Resources/values/colors.xml
  src/App.Android/Resources/values/styles.xml
  src/App.Android/SplashActivity.cs
Labels: UI

#23 Feature/minor ui tweaks
  src/App.Android/Resources/mipmap-hdpi/launcher_foreground.png
  src/App.iOS/App.iOS.csproj
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x-1.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x-1.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x-1.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x-2.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x-1.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon1024.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon120.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon152.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon167.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon180.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon20.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon29.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon40-1.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon40-2.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon40.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon58-1.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon58.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon60.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon76.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/Icon87.png
  src/App.iOS/Assets.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
  src/App.iOS/Assets.xcassets/Splash.imageset/Contents.json
  src/App.iOS/Assets.xcassets/Splash.imageset/Icon120-1.png
  src/App.iOS/Assets.xcassets/Splash.imageset/Icon120.png
  src/App.iOS/Assets.xcassets/Splash.imageset/Icon180-1.png
  src/App.iOS/Assets.xcassets/Splash.imageset/Icon180.png
  src/App.iOS/Assets.xcassets/Splash.imageset/Icon60-1.png
  src/App.iOS/Assets.xcassets/Splash.imageset/Icon60.png
  src/App.iOS/Info.plist
  src/App.iOS/Resources/Default-568h@2x.png
  src/App.iOS/Resources/Default-Portrait.png
  src/App.iOS/Resources/Default-Portrait@2x.png
  src/App.iOS/Resources/Default.png
  src/App.iOS/Resources/Default@2x.png
  src/App.iOS/Resources/LaunchScreen.storyboard
  src/App/MainShell.xaml
  src/App/Services/AppConstant.cs
  src/App/Views/JosbListView.xaml
Labels: enhancement
