Repository Emplea-do/MobileApp-Xamarin, pull requests merged in 2020-11, with the labels that each got.

#39 Feature/migration prism
  src/App.Android/App.Android.csproj
  src/App.Android/MainActivity.cs
  src/App.Android/Resources/Resource.designer.cs
  src/App.iOS/App.iOS.csproj
  src/App.iOS/AppDelegate.cs
  src/App/App.csproj
  src/App/App.xaml
  src/App/App.xaml.cs
  src/App/AssemblyInfo.cs
  src/App/Models/JobDetailModel.cs
  src/App/Models/JobListModel.cs
  src/App/Services/AppConstant.cs
  src/App/ViewModels/JobDetailViewModel.cs
  src/App/ViewModels/JobsListViewModel.cs
  src/App/ViewModels/SearchPageViewModel.cs
  src/App/Views/JobDetailView.xaml
  src/App/Views/JobDetailView.xaml.cs
  src/App/Views/JobsListView.xaml
  src/App/Views/JobsListView.xaml.cs
  src/App/Views/SearchView.xaml
  src/App/Views/SearchView.xaml.cs
Labels: UI, bug, enhancement

#41 Reaplacing CarouselView for Collection View
  src/App/Services/MockCardService.cs
  src/App/ViewModels/SearchPageViewModel.cs
  src/App/Views/SearchView.xaml
  src/App/Views/SearchView.xaml.cs
Labels: UI, bug

#45 Feature/main tabbed page
  src/.DS_Store
  src/App.Android/SplashActivity.cs
  src/App/App.csproj
  src/App/App.xaml.cs
  src/App/ViewModels/SearchViewModel.cs
  src/App/ViewModels/ViewModelBase.cs
  src/App/Views/MainTabbedPage.xaml
  src/App/Views/MainTabbedPage.xaml.cs
  src/App/Views/ProfileView.xaml
  src/App/Views/SearchView.xaml
  src/App/Views/SettingsView.xaml
Labels: bug, good first issue
